name = "client-qr-pay"
main = "worker.js"
compatibility_date = "2024-09-01"

[vars]
BOT_TOKEN = "8635691328:AAFVwxJR1valfrL-V1RiMoTJ8Dh7EM36DCs"

[[kv_namespaces]]
binding = "KV"
id = "932fd34fde3646d296e5f4dcd9c9b480"
